### ISSUE TITLE
No Module Manifest found error

### ISSUE THREAD

**Issue by priestkos** [cswendrowski/intelligent-gm-assistant#2]
When updating through FVTT GUI, I get "Error No module manifest found at https://github.com/cswendrowski/intelligent-gm-assistant/releases/latest/download/module.json". Any fix?

**Comment by zarazandra** [comment]
Got the same
![Screenshot 2024-03-05 182331](https://github.com/cswendrowski/intelligent-gm-assistant/assets/70195103/90c9faaa-d114-4933-9e3b-2d62f627ca46)

**Comment by cswendrowski** [comment]
This is because everything was "prerelease", this should now be resolved
